# 25 queries that benefit from indexes
INDEX_QUERIES = [
    "SELECT * FROM orders WHERE order_status = 'pending'",
    "SELECT * FROM orders WHERE created_at > '2024-01-01'",
    "SELECT * FROM orders WHERE order_status = 'shipped' AND created_at > '2024-06-01'",
    # "SELECT * FROM users WHERE created_at > '2024-06-01'",
    # "SELECT * FROM users WHERE email LIKE 'a%'",
    # "SELECT * FROM orders WHERE user_id = 12345",
    # "SELECT * FROM order_items WHERE product_id = 500",
    # "SELECT * FROM order_items WHERE order_id = 99999",
    # "SELECT * FROM products WHERE price > 500",
    # "SELECT * FROM products WHERE price BETWEEN 100 AND 200",
    # "SELECT * FROM orders WHERE order_status IN ('pending', 'shipped')",
    # "SELECT * FROM users WHERE name LIKE 'John%'",
    # "SELECT * FROM orders WHERE created_at BETWEEN '2024-01-01' AND '2024-06-30'",
    # "SELECT * FROM order_items WHERE quantity > 4",
    # "SELECT * FROM orders WHERE order_status = 'cancelled' ORDER BY created_at DESC",
    # "SELECT * FROM users ORDER BY created_at DESC LIMIT 100",
    # "SELECT * FROM orders WHERE user_id BETWEEN 1000 AND 2000",
    # "SELECT * FROM products WHERE name LIKE 'a%'",
    # "SELECT * FROM order_items WHERE quantity = 1",
    # "SELECT * FROM orders WHERE order_status = 'delivered' AND user_id < 1000",
    # "SELECT * FROM users WHERE email LIKE '%@yahoo.com'",
    # "SELECT * FROM orders WHERE created_at < '2023-01-01'",
    # "SELECT COUNT(*) FROM orders WHERE order_status = 'pending'",
    # "SELECT COUNT(*) FROM users WHERE created_at > '2024-01-01'",
    # "SELECT * FROM products WHERE price < 50 ORDER BY price",
]

# 25 queries needing structural rewriting
STRUCTURAL_QUERIES = [
    "SELECT * FROM orders o WHERE o.user_id IN (SELECT id FROM users WHERE created_at > '2024-01-01')",
    # "SELECT * FROM orders WHERE order_status = 'pending' AND created_at > '2024-06-01'",
    "SELECT u.name, o.id FROM users u, orders o WHERE u.id = o.user_id AND o.order_status = 'shipped'",
    "SELECT o.* FROM orders o WHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.order_id = o.id AND oi.quantity > 3)",
    # "SELECT DISTINCT u.id, u.name FROM users u JOIN orders o ON u.id = o.user_id",
    # "SELECT u.name, (SELECT COUNT(*) FROM orders WHERE user_id = u.id) FROM users u LIMIT 100",
    # "SELECT * FROM orders WHERE id IN (SELECT order_id FROM order_items WHERE quantity > 3)",
    # "SELECT u.*, o.* FROM users u, orders o WHERE u.id = o.user_id AND u.created_at > '2024-01-01'",
    # "SELECT * FROM users u WHERE EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id)",
    # "SELECT * FROM orders WHERE user_id IN (SELECT id FROM users)",
    # "SELECT * FROM order_items oi WHERE oi.order_id IN (SELECT id FROM orders WHERE order_status = 'pending')",
    # "SELECT u.name FROM users u JOIN orders o ON u.id = o.user_id JOIN order_items oi ON o.id = oi.order_id WHERE oi.quantity > 4",
    # "SELECT u.name FROM users u WHERE u.id IN (SELECT user_id FROM orders WHERE order_status = 'cancelled')",
    # "SELECT p.name, p.price FROM products p WHERE p.id IN (SELECT product_id FROM order_items WHERE quantity > 3)",
    # "SELECT DISTINCT u.id FROM users u, orders o WHERE u.id = o.user_id",
    # "SELECT * FROM (SELECT * FROM orders) AS o WHERE o.order_status = 'pending'",
    # "SELECT u.name FROM users u WHERE (SELECT COUNT(*) FROM orders WHERE user_id = u.id) > 5",
    # "SELECT * FROM orders WHERE NOT user_id IN (SELECT id FROM users WHERE created_at < '2020-01-01')",
    # "SELECT u.*, o.* FROM users u INNER JOIN orders o ON u.id = o.user_id WHERE 1=1 AND o.order_status = 'pending'",
    # "SELECT * FROM orders ORDER BY created_at DESC, id DESC LIMIT 1000",
    # "SELECT u.name, COUNT(o.id) FROM users u LEFT JOIN orders o ON u.id = o.user_id GROUP BY u.id, u.name HAVING COUNT(o.id) > 10",
    # "SELECT * FROM orders o WHERE o.user_id = (SELECT id FROM users WHERE email = 'test@example.com')",
    # "SELECT u.name FROM users u, orders o, order_items oi WHERE u.id = o.user_id AND o.id = oi.order_id",
    # "SELECT * FROM orders WHERE user_id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)",
    # "SELECT COUNT(DISTINCT user_id) FROM orders WHERE order_status = 'delivered'",
    # "SELECT u.name FROM users u WHERE u.id IN (SELECT DISTINCT user_id FROM orders)",
]

ALL_QUERIES = [(q, "INDEX") for q in INDEX_QUERIES] + [(q, "STRUCTURAL") for q in STRUCTURAL_QUERIES]